/**
 * Interface representing a material tracking event in the system
 */
interface MaterialTrackingEvent {
  /** Unique identifier for the event */
  event_id?: number;

  /**
   * Company associated with the event
   * - For admin portal: relates to "companies"
   * - For app submission: links to user's profile/company
   */
  company?: string;

  /** Timestamp when the QR code was captured (automatically generated by app) */
  event_timestamp?: Date;

  /** Geographic coordinates (longitude/latitude) from device location services */
  event_location?: string;

  /** Name of the action from Actions table, max length 255 characters */
  action?: string;

  /** Name of the collector (relates to "collectors" table) */
  collector_name?: string;

  /** QR code identifier for input material or collector QR card */
  event_input_id?: number;

  /** QR code identifier for output material or product URL */
  event_output_id?: number;

  /**
   * Identifier for the production entry
   * Note: Used for tracing, a pellet may be used in multiple productions
   */
  production_id?: number;

  /**
   * Relation to weight slip (many-to-one relationship)
   * Note: Sponsor information moved to weight slip
   */
  weight_slip_id?: number;

  /** EAS Attestation identifier, max length 255 characters */
  UID?: string;

  /** Timestamp for EAS attestation */
  eas_timestamp?: Date;
}

/**
 * Interface representing a material output record in the system
 */
interface MaterialOutputRecord {
  /** Unique identifier for the output entry */
  event_output_id?: number;

  /** Event ID related to the output entry */
  event_id?: number;

  /** QR code for the output material or production_url */
  output_code: string;

  /**
   * Reference to material_id from Materials table
   * Optional when event is manufacturing (added Nov/11)
   */
  output_material?: number;

  /**
   * Weight of the output material(s) in Kg
   * Optional when event is manufacturing (added Nov/11)
   */
  output_weight?: number;
}

/**
 * Interface representing a material input record in the system
 */
interface MaterialInputRecord {
  /** Unique identifier for the input entry */
  event_input_id?: number;

  /** Event ID related to the input entry */
  event_id?: number;

  /** QR code for input material or collector QR card */
  input_code: string;

  /** Reference to material_id from Materials table */
  input_material: number;

  /** Weight of the input material(s) in Kg */
  input_weight: number;
}

export type {
  MaterialTrackingEvent,
  MaterialOutputRecord,
  MaterialInputRecord,
};
